const brands = [
    { id: '1', name: 'Audi', logo: require('../../assets/car_logo/audi.png'), tagline:'Progress through Technology' },
    { id: '2', name: 'BMW', logo: require('../../assets/car_logo/bmw.png'), tagline:'The Ultimate Driving Machine'},
    { id: '3', name: 'Porsche', logo: require('../../assets/car_logo/porsche.png'), tagline:'There Is No Substitute' },
    { id: '4', name: 'Mercedes Benz', logo: require('../../assets/car_logo/mercedes.png'), tagline:'The Best or Nothing' },
    { id: '5', name: 'Rolls Royce', logo: require('../../assets/car_logo/rolls_royce.png'), tagline:'Inspiring Greatness' },
    { id: '6', name: 'Toyota', logo: require('../../assets/car_logo/toyota.png'), tagline:'Lets Go Places' },
    { id: '7', name: 'Honda', logo: require('../../assets/car_logo/honda.png'), tagline:'The Power of Dreams' },
    { id: '8', name: 'Nissan', logo: require('../../assets/car_logo/nissan.png'), tagline:'Driving innovation to enrich peoples lives' },
    { id: '9', name: 'Ford', logo: require('../../assets/car_logo/ford.png'), tagline:'Built Ford Tough' },
    { id: '10', name: 'Chevrolet', logo: require('../../assets/car_logo/chevy.png'), tagline:'Together Lets Drive' },
    { id: '11', name: 'Hyundai', logo: require('../../assets/car_logo/hyundai.png'), tagline:'New Thinking. New Possibilities' },
    { id: '12', name: 'Mazda', logo: require('../../assets/car_logo/mazda.png'), tagline:'Zoom-Zoom' },
  ];

const brandData = {
    cars: {
      Audi: [
        {
          id: 'a1',
          name: 'Audi A4',
          type: 'Sedan',
          price: '₱ 3,450,000',
          description: 'A sleek and stylish compact executive car renowned for its bold design, advanced technology, and premium interior features—perfectly blending performance, comfort, and innovation for modern drivers.',
          images: [
            require('../../assets/brands/audi/a4-6.jpg'),
            require('../../assets/brands/audi/a4-1.jpg'),
            require('../../assets/brands/audi/a4-2.jpg'),
            require('../../assets/brands/audi/a4-3.jpg'),
            require('../../assets/brands/audi/a4-5.jpg'),
          ],
          specs: [
            'Engine: 2.0L 4-Cylinder Turbo',
            'Transmission: 7-speed dual-clutch automatic',
            'Drivetrain: AWD',
            'Horsepower: 207 hp',
            'Torque: 320 nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'a2',
          name: 'Audi Q5',
          type: 'SUV / Crossover',
          price: '₱ 5,650,000',
          description: 'The Audi Q5 is a luxury compact SUV that masterfully blends performance, style, and cutting-edge technology to deliver a refined and dynamic driving experience. With its elegant design, signature LED lighting, and bold grille, the Q5 stands out on the road while maintaining a sense of understated sophistication.',
          images: [
            require('../../assets/brands/audi/q5-1.jpg'),
            require('../../assets/brands/audi/q5-2.jpg'),
            require('../../assets/brands/audi/q5-3.jpg'),
            require('../../assets/brands/audi/q5-4.jpg'),
            require('../../assets/brands/audi/q5-5.jpg'),
          ],
          specs: [
            'Engine: 2.0L 4-Cylinder Turbo',
            'Transmission: 7-Speed Auto-Shift Manual',
            'Drivetrain: AWD',
            'Horsepower: 201 hp',
            'Torque: 320 nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'a3',
          name: 'Audi R8',
          type: 'Coupe / Convertible',
          price: '₱ 12,000,000',
          description: 'A breathtaking high-performance supercar, the Audi R8 combines race-inspired engineering with sleek design and everyday drivability, delivering an exhilarating experience both on the road and the track.',
          images: [
            require('../../assets/brands/audi/r8-1.jpg'),
            require('../../assets/brands/audi/r8-2.jpg'),
            require('../../assets/brands/audi/r8-5.jpg'),
            require('../../assets/brands/audi/r8-3.jpg'),
            require('../../assets/brands/audi/r8-4.jpg'),
          ],
          specs: [
            'Engine: 5.2L 10-Cylinder Turbo',
            'Transmission: 8-speed Tiptronic automatic',
            'Drivetrain: AWD',
            'Horsepower: 602 hp',
            'Torque: 560 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'a4',
          name: 'Audi SQ8',
          type: 'SUV / Crossover',
          price: '₱ 5,900,000',
          description: 'The Audi SQ8 is a premium performance SUV that combines bold styling with sporty sophistication, offering a dynamic driving experience wrapped in luxurious comfort and advanced technology.',
          images: [
            require('../../assets/brands/audi/sq8-1.jpg'),
            require('../../assets/brands/audi/sq8-2.jpg'),
            require('../../assets/brands/audi/sq8-3.jpg'),
            require('../../assets/brands/audi/sq8-4.jpg'),
            require('../../assets/brands/audi/sq8-5.jpg'),
          ],
          specs: [
            'Engine: 4.0L 8-Cylinder Twin-Turbo',
            'Transmission: 7-Speed S tronic dual-clutch',
            'Drivetrain: AWD',
            'Horsepower: 500 hp',
            'Torque: 770 Nm',
            'Fuel Type: Electric',
          ],
        },
        {
          id: 'a5',
          name: 'Audi RS7',
          type: 'Coupe / Convertible',
          price: '₱ 7,200,000',
          description: 'The Audi RS7 is a high-performance luxury Sportback that blends aggressive design with exhilarating power, offering thrilling performance, cutting-edge tech, and everyday refinement in a sleek, five-door silhouette.',
          images: [
            require('../../assets/brands/audi/rs7-1.jpg'),
            require('../../assets/brands/audi/rs7-2.jpg'),
            require('../../assets/brands/audi/rs7-3.jpg'),
            require('../../assets/brands/audi/rs7-4.jpg'),
            require('../../assets/brands/audi/rs7-5.jpg'),
          ],
          specs: [
            'Engine: 4.0L 8-Cylinder Twin-Turbo',
            'Transmission: 8-Speed Tiptronic Automatic',
            'Drivetrain: AWD',
            'Horsepower: 621 hp',
            'Torque: 850 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'a6',
          name: 'Audi S8',
          type: 'Sedan',
          price: '₱ 7,900,000',
          description: 'The Audi S8 is a high-performance luxury sedan that delivers a perfect fusion of executive comfort and dynamic power, wrapped in an elegant and commanding design.',
          images: [
            require('../../assets/brands/audi/s8-1.jpg'),
            require('../../assets/brands/audi/s8-2.jpg'),
            require('../../assets/brands/audi/s8-3.jpg'),
            require('../../assets/brands/audi/s8-4.jpg'),
            require('../../assets/brands/audi/s8-5.jpg'),
          ],
          specs: [
            'Engine: 4.0L 8-Cylinder Twin-Turbo',
            'Transmission: 8-Speed Tiptronic Automatic',
            'Drivetrain: AWD',
            'Horsepower: 563 hp',
            'Torque: 805 Nm',
            'Fuel Type: Gasoline',
          ],
        },
      ],
    /************************************************************* BMW **********************************************************/   
      BMW: [
        {
            id: 'b1',
            name: 'BMW 760 i',
            type: 'Sedan',
            price: '₱ 9,000,000',
            description: 'The BMW 760i is a luxury full-size sedan that combines elegant design with cutting-edge technology and powerful performance. It features a 4.4-liter twin-turbo V8 engine with mild-hybrid tech, delivering smooth acceleration and a refined driving experience. ',
            images: [
              require('../../assets/brands/bmw/760i-1.jpg'),
              require('../../assets/brands/bmw/760i-2.jpg'),
              require('../../assets/brands/bmw/760i-3.jpg'),
              require('../../assets/brands/bmw/760i-4.jpg'),
              require('../../assets/brands/bmw/760i-5.jpg'),
            ],
            specs: [
              'Engine: 3.0L 8-Cylinder Twin-Turbo',
              'Transmission: 8-Speed Automatic',
              'Drivetrain: AWD',
              'Horsepower: 536 hp',
              'Torque: 750 Nm',
              'Fuel Type: Gasoline',
            ],
          },
       
        {
            id: 'b2',
            name: 'BMW X7',
            type: 'SUV / Crossover',
            price: '₱ 10,600,000',
            description: 'The BMW X7 is a flagship luxury SUV that offers a commanding presence, elegant design, and a spacious, high-end interior. It combines premium comfort with advanced technology and delivers a smooth, confident driving experience. Ideal for those who value luxury and versatility in a full-size SUV.',
            images: [
              require('../../assets/brands/bmw/x7-1.jpg'),
              require('../../assets/brands/bmw/x7-2.jpg'),
              require('../../assets/brands/bmw/x7-3.jpg'),
              require('../../assets/brands/bmw/x7-4.jpg'),
              require('../../assets/brands/bmw/x7-5.jpg'),
            ],
            specs: [
              'Engine: 4.4L 8-Cylinder Turbo',
              'Transmission: 8-Speed Automatic',
              'Drivetrain: AWD',
              'Horsepower: 523 hp',
              'Torque: 539 Nm',
              'Fuel Type: Gasoline',
            ],
          },
        {
            id: 'b3',
            name: 'BMW M8',
            type: 'Coupe / Convertible',
            price: '₱ 12,890,000',
            description: 'The BMW M8 is a high-performance luxury coupe that blends sleek design with dynamic driving capabilities. It features bold styling, a refined interior, and cutting-edge technology, offering an exhilarating experience while maintaining the comfort and elegance expected from a BMW.',
            images: [
              require('../../assets/brands/bmw/m8-1.jpg'),
              require('../../assets/brands/bmw/m8-2.jpg'),
              require('../../assets/brands/bmw/m8-3.jpg'),
              require('../../assets/brands/bmw/m8-4.jpg'),
              require('../../assets/brands/bmw/m8-5.jpg'),
            ],
            specs: [
              'Engine: 4.4L 8-Cylinder Twin-Turbo',
              'Transmission: 8-Speed Automatic',
              'Drivetrain: AWD',
              'Horsepower: 617 hp',
              'Torque: 750 Nm',
              'Fuel Type: Gasoline',
            ],
          },

        {
            id: 'b4',
            name: 'BMW 840i',
            type: 'Sedan',
            price: '₱ 9,290,000',
            description: 'The BMW 840i is a sleek and sophisticated luxury coupe that combines refined design with engaging performance. It offers a smooth and comfortable ride, a premium interior, and advanced technology, making it ideal for drivers who value both elegance and driving pleasure.',
            images: [
              require('../../assets/brands/bmw/840i-1.jpg'),
              require('../../assets/brands/bmw/840i-2.jpg'),
              require('../../assets/brands/bmw/840i-3.jpg'),
              require('../../assets/brands/bmw/840i-4.jpg'),
              require('../../assets/brands/bmw/840i-5.jpg'),
            ],
            specs: [
              'Engine: 3.0L 6-Cylinder TwinPower Turbo',
              'Transmission: 8-Speed Automatic',
              'Drivetrain: RWD',
              'Horsepower: 335 hp',
              'Torque: 500 Nm',
              'Fuel Type: Gasoline',
            ],
          },

        {
            id: 'b5',
            name: 'BMW XM',
            type: 'SUV / Crossover',
            price: '₱ 15,890,000',
            description: 'The BMW XM is a bold and luxurious high-performance SUV that marks a new era for BMW M. It features a striking design, an opulent interior, and cutting-edge technology, combining electrified power with the thrilling performance expected from the M division.',
            images: [
              require('../../assets/brands/bmw/xm-1.jpg'),
              require('../../assets/brands/bmw/xm-2.jpg'),
              require('../../assets/brands/bmw/xm-3.jpg'),
              require('../../assets/brands/bmw/xm-4.jpg'),
              require('../../assets/brands/bmw/xm-5.jpg'),
            ],
            specs: [
              'Engine: 4.4L 8-Cylinder Twin-Turbo',
              'Transmission: 8-Speed M Steptronic Automatic',
              'Drivetrain: AWD',
              'Horsepower: 644 hp',
              'Torque: 800 Nm',
              'Fuel Type: Hybrid',
            ],
          },
      ],
    /************************************************************* Porsche **********************************************************/   
    Porsche: [
        {
          id: 'p1',
          name: 'Porsche 911 Carrera',
          type: 'Coupe / Convertible',
          price: '₱ 12,000,000',
          description: 'The Porsche 911 Carrera is an iconic sports car that combines timeless design with exhilarating performance. It offers a perfect balance of everyday usability and track-ready dynamics.',
          images: [
            require('../../assets/brands/porsche/911-1.jpg'),
            require('../../assets/brands/porsche/911-2.jpg'),
            require('../../assets/brands/porsche/911-3.jpg'),
            require('../../assets/brands/porsche/911-4.jpg'),
            require('../../assets/brands/porsche/911-5.jpg'),
          ],
          specs: [
            'Engine: 3.0L Twin-Turbo Flat-6',
            'Transmission: 8-Speed PDK Automatic',
            'Drivetrain: RWD',
            'Horsepower: 379 hp',
            'Torque: 450 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'p2',
          name: 'Porsche Cayenne',
          type: 'SUV / Crossover',
          price: '₱ 9,000,000',
          description: 'The Porsche Cayenne is a luxury SUV that offers sporty performance, advanced technology, and versatile practicality, making it suitable for both city driving and off-road adventures.',
          images: [
            require('../../assets/brands/porsche/cayenne-1.jpg'),
            require('../../assets/brands/porsche/cayenne-2.jpg'),
            require('../../assets/brands/porsche/cayenne-3.jpg'),
            require('../../assets/brands/porsche/cayenne-4.jpg'),
            require('../../assets/brands/porsche/cayenne-5.jpg'),
          ],
          specs: [
            'Engine: 3.0L 6-Cylinder Twin-Turbo ',
            'Transmission: 8-Speed Automatic',
            'Drivetrain: AWD',
            'Horsepower: 348 hp',
            'Torque: 500 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'p3',
          name: 'Porsche Macan',
          type: 'SUV / Crossover',
          price: '₱ 6,500,000',
          description: 'The Porsche Macan is a compact SUV that delivers the performance and handling of a sports car, combined with the practicality and comfort of an SUV.',
          images: [
            require('../../assets/brands/porsche/macan-1.jpg'),
            require('../../assets/brands/porsche/macan-2.jpg'),
            require('../../assets/brands/porsche/macan-3.jpg'),
            require('../../assets/brands/porsche/macan-4.jpg'),
            require('../../assets/brands/porsche/macan-5.jpg'),
          ],
          specs: [
            'Engine: 2.0L 4-Cylinder Turbocharged',
            'Transmission: 7-Speed PDK Automatic',
            'Drivetrain: AWD',
            'Horsepower: 265 hp',
            'Torque: 400 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'p4',
          name: 'Porsche Panamera',
          type: 'Sedan',
          price: '₱ 10,000,000',
          description: 'The Porsche Panamera is a luxury sedan that combines sports car performance with executive comfort, offering a dynamic driving experience with cutting-edge technology.',
          images: [
            require('../../assets/brands/porsche/panamera-1.jpg'),
            require('../../assets/brands/porsche/panamera-2.jpg'),
            require('../../assets/brands/porsche/panamera-3.jpg'),
            require('../../assets/brands/porsche/panamera-4.jpg'),
            require('../../assets/brands/porsche/panamera-5.jpg'),
          ],
          specs: [
            'Engine: 2.9L 6-Cylinder Twin-Turbo',
            'Transmission: 8-Speed PDK Automatic',
            'Drivetrain: RWD',
            'Horsepower: 353 hp',
            'Torque: 500 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'p5',
          name: 'Porsche Taycan',
          type: 'Sedan',
          price: '₱ 9,500,000',
          description: 'The Porsche Taycan is an all-electric sports sedan that delivers thrilling performance, cutting-edge technology, and sustainable mobility without compromising on luxury.',
          images: [
            require('../../assets/brands/porsche/taycan-1.jpg'),
            require('../../assets/brands/porsche/taycan-2.jpg'),
            require('../../assets/brands/porsche/taycan-3.jpg'),
            require('../../assets/brands/porsche/taycan-4.jpg'),
            require('../../assets/brands/porsche/taycan-5.jpg'),
          ],
          specs: [
            'Engine: Dual Electric Motors',
            'Transmission: 2-Speed Automatic',
            'Drivetrain: AWD',
            'Horsepower: 616 hp (up to 750 hp with overboost)',
            'Torque: 850 Nm',
            'Fuel Type: Electric',
          ],
        },
      ],      
    /************************************************************* Mercedes-Benz  **********************************************************/   
    'Mercedes Benz': [
        {
            id: 'm1',
            name: 'Mercedes Benz S-Class',
            type: 'Sedan',
            price: '₱ 10,500,000',
            description: 'The Mercedes-Benz S-Class is the pinnacle of luxury sedans, offering unparalleled comfort, advanced technology, and refined performance. It sets the standard for executive travel.',
            images: [
              require('../../assets/brands/mercedes/sclass-1.jpg'),
              require('../../assets/brands/mercedes/sclass-2.jpg'),
              require('../../assets/brands/mercedes/sclass-3.jpg'),
              require('../../assets/brands/mercedes/sclass-4.jpg'),
              require('../../assets/brands/mercedes/sclass-5.jpg'),
            ],
            specs: [
              'Engine: 4.0L 8-Cylinder Twin-Turbo with Mild Hybrid Drive',
              'Transmission: 9-Speed Automatic',
              'Drivetrain: AWD',
              'Horsepower: 496 hp',
              'Torque: 700 Nm',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 'm2',
            name: 'Mercedes Benz GLE',
            type: 'SUV / Crossover',
            price: '₱ 7,800,000',
            description: 'The Mercedes-Benz GLE is a versatile luxury SUV that combines spaciousness, cutting-edge technology, and dynamic performance, making it ideal for both city driving and off-road adventures.',
            images: [
              require('../../assets/brands/mercedes/gle-1.jpg'),
              require('../../assets/brands/mercedes/gle-2.jpg'),
              require('../../assets/brands/mercedes/gle-3.jpg'),
              require('../../assets/brands/mercedes/gle-4.jpg'),
              require('../../assets/brands/mercedes/gle-5.jpeg'),
            ],
            specs: [
              'Engine: 3.0L 6-Cylinder Turbo with Mild Hybrid Drive',
              'Transmission: 9-Speed Automatic',
              'Drivetrain: AWD',
              'Horsepower: 362 hp',
              'Torque: 500 Nm',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 'm3',
            name: 'Mercedes-Benz CLE',
            type: 'Coupe / Convertible',
            price: '₱ 5,800,000',
            description: 'The Mercedes-Benz CLE 300 4MATIC is a stylish and sporty coupe that merges the best features of the C-Class and E-Class. It delivers a refined yet exhilarating driving experience with advanced tech and elegant design.',
            images: [
              require('../../assets/brands/mercedes/cle-1.jpg'),
              require('../../assets/brands/mercedes/cle-2.jpg'),
              require('../../assets/brands/mercedes/cle-3.jpg'),
              require('../../assets/brands/mercedes/cle-4.jpg'),
              require('../../assets/brands/mercedes/cle-5.jpg'),
            ],
            specs: [
              'Engine: 2.0L 4-Cylinder Turbo with Mild Hybrid Drive',
              'Transmission: 9-Speed Automatic',
              'Drivetrain: AWD',
              'Horsepower: 255 hp',
              'Torque: 400 Nm',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 'm4',
            name: 'Mercedes-Benz EQE',
            type: 'Sedan',
            price: '₱ 8,200,000',
            description: 'The Mercedes-Benz EQE 350+ is a luxury electric sedan that combines futuristic design, advanced technology, and smooth electric performance. It offers a quiet, refined ride with zero emissions and premium comfort throughout.',
            images: [
              require('../../assets/brands/mercedes/eqe-1.jpg'),
              require('../../assets/brands/mercedes/eqe-2.jpg'),
              require('../../assets/brands/mercedes/eqe-3.jpg'),
              require('../../assets/brands/mercedes/eqe-4.jpg'),
              require('../../assets/brands/mercedes/eqe-5.jpg'),
            ],
            specs: [
              'Engine: Single Electric Motor',
              'Transmission: Single-Speed Automatic',
              'Drivetrain: RWD',
              'Horsepower: 288 hp',
              'Torque: 565 Nm',
              'Fuel Type: Electric',
            ],
          },
          {
            id: 'm5',
            name: 'Mercedes Benz G-Class',
            type: 'SUV / Crossover',
            price: '₱ 15,000,000',
            description: 'The Mercedes-Benz G-Class is an iconic luxury SUV known for its rugged design, exceptional off-road capabilities, and premium features, offering a unique blend of performance and style.',
            images: [
              require('../../assets/brands/mercedes/gclass-1.jpg'),
              require('../../assets/brands/mercedes/gclass-2.jpg'),
              require('../../assets/brands/mercedes/gclass-3.jpg'),
              require('../../assets/brands/mercedes/gclass-4.jpg'),
              require('../../assets/brands/mercedes/gclass-5.jpg'),
            ],
            specs: [
              'Engine: 4.0L 8-Cylinder Twin-Turbo',
              'Transmission: 9-Speed Automatic',
              'Drivetrain: AWD',
              'Horsepower: 577 hp',
              'Torque: 850 Nm',
              'Fuel Type: Gasoline',
            ],
          },
      ],    
    /************************************************************* Rolls Royce  **********************************************************/   
    'Rolls Royce': [
        {
            id: 'rr1',
            name: 'Rolls-Royce Phantom',
            type: 'Sedan',
            price: '₱ 46,000,000',
            description: 'The Rolls-Royce Phantom is the pinnacle of luxury sedans, offering unparalleled craftsmanship, timeless design, and a serene driving experience. It embodies the essence of opulence and sophistication.',
            images: [
              require('../../assets/brands/rolls-royce/phantom-1.jpg'),
              require('../../assets/brands/rolls-royce/phantom-2.jpg'),
              require('../../assets/brands/rolls-royce/phantom-3.jpg'),
              require('../../assets/brands/rolls-royce/phantom-4.png'),
              require('../../assets/brands/rolls-royce/phantom-5.jpg'),
            ],
            specs: [
              'Engine: 6.75L 12-Cylinder Twin-Turbo',
              'Transmission: 8-Speed Automatic',
              'Drivetrain: RWD',
              'Horsepower: 563 hp',
              'Torque: 664 lb-ft',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 'rr2',
            name: 'Rolls-Royce Ghost',
            type: 'Sedan',
            price: '₱ 32,000,000',
            description: 'The Rolls-Royce Ghost combines dynamic performance with refined luxury, delivering a driving experience that is both exhilarating and supremely comfortable.',
            images: [
              require('../../assets/brands/rolls-royce/ghost-1.jpg'),
              require('../../assets/brands/rolls-royce/ghost-2.jpg'),
              require('../../assets/brands/rolls-royce/ghost-3.jpg'),
              require('../../assets/brands/rolls-royce/ghost-4.jpg'),
              require('../../assets/brands/rolls-royce/ghost-5.jpg'),
            ],
            specs: [
              'Engine: 6.75L 12-Cylinder Twin-Turbo',
              'Transmission: 8-Speed Automatic',
              'Drivetrain: AWD',
              'Horsepower: 563 hp',
              'Torque: 627 lb-ft',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 'rr3',
            name: 'Rolls-Royce Cullinan',
            type: 'SUV / Crossover',
            price: '₱ 38,000,000',
            description: 'The Rolls-Royce Cullinan is the epitome of luxury SUVs, offering exceptional comfort, advanced technology, and the capability to traverse any terrain with grace.',
            images: [
              require('../../assets/brands/rolls-royce/cullinan-1.jpg'),
              require('../../assets/brands/rolls-royce/cullinan-2.jpg'),
              require('../../assets/brands/rolls-royce/cullinan-3.jpg'),
              require('../../assets/brands/rolls-royce/cullinan-4.jpg'),
              require('../../assets/brands/rolls-royce/cullinan-5.jpg'),
            ],
            specs: [
              'Engine: 6.75L 12-Cylinder Twin-Turbo',
              'Transmission: 8-Speed Automatic',
              'Drivetrain: AWD',
              'Horsepower: 563 hp',
              'Torque: 627 lb-ft',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 'rr4',
            name: 'Rolls-Royce Dawn',
            type: 'Coupe / Convertible',
            price: '₱ 34,000,000',
            description: 'The Rolls-Royce Dawn is a luxurious convertible that offers open-top elegance and a serene, refined driving experience. It features timeless styling, meticulous craftsmanship, and smooth, effortless performance.',
            images: [
              require('../../assets/brands/rolls-royce/dawn-1.jpg'),
              require('../../assets/brands/rolls-royce/dawn-2.jpg'),
              require('../../assets/brands/rolls-royce/dawn-3.jpg'),
              require('../../assets/brands/rolls-royce/dawn-4.jpg'),
              require('../../assets/brands/rolls-royce/dawn-5.jpg'),
            ],
            specs: [
              'Engine: 6.6L 12-Cylinder Twin-Turbo',
              'Transmission: 8-Speed Automatic',
              'Drivetrain: RWD',
              'Horsepower: 563 hp',
              'Torque: 820 Nm',
              'Fuel Type: Gasoline',
            ],
          }
          
      ],    


    /************************************************************* Toyota  **********************************************************/   
    Toyota: [
        {
            id: 't1',
            name: 'Toyota GR Supra',
            type: 'Coupe / Convertible',
            price: '₱ 5,396,000',
            description: 'The Toyota GR Supra is a high-performance sports coupe that delivers thrilling driving dynamics, sleek design, and advanced technology. It offers an exhilarating experience for enthusiasts seeking precision and power.',
            images: [
              require('../../assets/brands/toyota/supra-1.jpg'),
              require('../../assets/brands/toyota/supra-2.jpg'),
              require('../../assets/brands/toyota/supra-3.jpg'),
              require('../../assets/brands/toyota/supra-4.jpeg'),
              require('../../assets/brands/toyota/supra-5.jpg'),
            ],
            specs: [
              'Engine: 6-Cylinder Twin-Scroll Turbocharged',
              'Transmission: 8-Speed Automatic',
              'Drivetrain: RWD',
              'Horsepower: 387 hp',
              'Torque: 500 Nm',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 't2',
            name: 'Toyota Camry',
            type: 'Sedan',
            price: '₱ 2,442,000',
            description: 'The Toyota Camry is a premium midsize sedan that combines elegant styling with a comfortable ride and advanced safety features. It offers a refined driving experience suitable for both city and highway journeys.',
            images: [
              require('../../assets/brands/toyota/camry-1.jpg'),
              require('../../assets/brands/toyota/camry-2.jpg'),
              require('../../assets/brands/toyota/camry-3.jpg'),
              require('../../assets/brands/toyota/camry-4.jpg'),
              require('../../assets/brands/toyota/camry-5.jpg'),
            ],
            specs: [
              'Engine: 4-Cylinder Hybrid',
              'Transmission: CVT',
              'Drivetrain: FWD',
              'Horsepower: 176 hp',
              'Torque: 221 Nm',
              'Fuel Type: Hybrid',
            ],
          },
          {
            id: 't3',
            name: 'Toyota Alphard',
            type: 'Minivan / MPV',
            price: '₱ 4,980,000',
            description: 'The Toyota Alphard is a luxurious minivan that offers spacious seating, premium comfort, and advanced features. It is designed for those who prioritize luxury and convenience in their travels.',
            images: [
              require('../../assets/brands/toyota/alphard-1.jpg'),
              require('../../assets/brands/toyota/alphard-2.jpg'),
              require('../../assets/brands/toyota/alphard-3.jpg'),
              require('../../assets/brands/toyota/alphard-4.jpg'),
              require('../../assets/brands/toyota/alphard-5.jpg'),
            ],
            specs: [
              'Engine: 4-Cylinder Hybrid',
              'Transmission: CVT',
              'Drivetrain: FWD',
              'Horsepower: 247 hp',
              'Torque: 221 Nm',
              'Fuel Type: Hybrid',
            ],
          },
          {
            id: 't4',
            name: 'Toyota Land Cruiser',
            type: 'SUV / Crossover',
            price: '₱ 5,390,000',
            description: 'The Toyota Land Cruiser is a legendary SUV known for its off-road prowess, durability, and luxurious features. It is built to conquer challenging terrains while providing comfort and reliability.',
            images: [
              require('../../assets/brands/toyota/lc-1.jpg'),
              require('../../assets/brands/toyota/lc-2.jpg'),
              require('../../assets/brands/toyota/lc-3.jpg'),
              require('../../assets/brands/toyota/lc-4.jpg'),
              require('../../assets/brands/toyota/lc-5.jpeg'),
            ],
            specs: [
              'Engine: 4-Cylinder Turbocharged',
              'Transmission: 8-Speed Automatic',
              'Drivetrain: 4WD',
              'Horsepower: 326 hp',
              'Torque: 630 Nm',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 't5',
            name: 'Toyota Hilux GR-S',
            type: 'Pickup Truck',
            price: '₱ 2,186,000',
            description: 'The Toyota Hilux GR-S is a rugged pickup truck that combines robust performance with sporty styling. It is equipped to handle tough terrains while offering modern amenities and safety features.',
            images: [
              require('../../assets/brands/toyota/hilux-1.jpg'),
              require('../../assets/brands/toyota/hilux-2.jpg'),
              require('../../assets/brands/toyota/hilux-3.jpg'),
              require('../../assets/brands/toyota/hilux-4.jpg'),
              require('../../assets/brands/toyota/hilux-5.jpg'),
            ],
            specs: [
              'Engine: 4-Cylinder Turbocharged Diesel',
              'Transmission: 6-Speed Automatic',
              'Drivetrain: 4WD',
              'Horsepower: 224 hp',
              'Torque: 550 Nm',
              'Fuel Type: Diesel',
            ],
          },
          {
            id: 't6',
            name: 'Toyota Yaris Cross',
            type: 'SUV / Crossover',
            price: '₱ 1,598,000',
            description: 'The Toyota Yaris Cross is a compact SUV that offers a blend of efficiency, style, and practicality. It is ideal for urban driving and weekend getaways, featuring modern technology and safety features.',
            images: [
              require('../../assets/brands/toyota/yaris-1.jpg'),
              require('../../assets/brands/toyota/yaris-2.jpg'),
              require('../../assets/brands/toyota/yaris-3.jpg'),
              require('../../assets/brands/toyota/yaris-4.jpg'),
              require('../../assets/brands/toyota/yaris-5.jpg'),
            ],
            specs: [
              'Engine: 4-Cylinder Hybrid',
              'Transmission: CVT',
              'Drivetrain: FWD',
              'Horsepower: 90 hp',
              'Torque: 121 Nm',
              'Fuel Type: Hybrid',
            ],
          },
          {
            id: 't7',
            name: 'Toyota Super Grandia',
            type: 'Minivan / MPV',
            price: '₱ 3,100,000',
            description: 'The Toyota Super Grandia is a premium van designed for executive transport, offering spacious interiors, upscale features, and a smooth ride. It’s ideal for comfortable long-distance travel or VIP shuttle services.',
            images: [
              require('../../assets/brands/toyota/grandia-1.jpg'),
              require('../../assets/brands/toyota/grandia-2.jpg'),
              require('../../assets/brands/toyota/grandia-3.jpg'),
              require('../../assets/brands/toyota/grandia-4.jpg'),
              require('../../assets/brands/toyota/grandia-5.jpg'),
            ],
            specs: [
              'Engine: 4-Cylinder 2.8L Diesel',
              'Transmission: 6-Speed Automatic',
              'Drivetrain: RWD',
              'Horsepower: 174 hp',
              'Torque: 450 Nm',
              'Fuel Type: Diesel',
            ],
          },
          {
            id: 't8',
            name: 'Toyota Tundra',
            type: 'Pickup Truck',
            price: '₱ 5,500,000',
            description: 'The Toyota Tundra is a powerful full-size pickup truck designed for heavy-duty tasks and off-road capability. It offers rugged durability, modern tech features, and a bold presence, making it a strong choice for both work and lifestyle needs.',
            images: [
              require('../../assets/brands/toyota/tundra-1.jpg'),
              require('../../assets/brands/toyota/tundra-2.jpg'),
              require('../../assets/brands/toyota/tundra-3.jpg'),
              require('../../assets/brands/toyota/tundra-4.jpg'),
              require('../../assets/brands/toyota/tundra-5.jpg'),
            ],
            specs: [
              'Engine: 8-Cylinder 3.4L Twin-Turbo Hybrid (i-FORCE MAX)',
              'Transmission: 10-Speed Automatic',
              'Drivetrain: 4WD',
              'Horsepower: 437 hp',
              'Torque: 790 Nm',
              'Fuel Type: Hybrid',
            ],
          }
          
          
          
      ],    


    /************************************************************* Honda  **********************************************************/   
    Honda: [
        {
            id: 'h1',
            name: 'Honda Civic Type R',
            type: 'Hatchback',
            price: '₱ 3,880,000',
            description: 'The Honda Civic Type R is a track-ready hot hatch that delivers exhilarating performance with aggressive styling. It offers precision handling, a powerful turbocharged engine, and a race-inspired interior for true driving enthusiasts.',
            images: [
              require('../../assets/brands/honda/typer-1.jpg'),
              require('../../assets/brands/honda/typer-2.jpg'),
              require('../../assets/brands/honda/typer-3.jpg'),
              require('../../assets/brands/honda/typer-4.jpg'),
              require('../../assets/brands/honda/typer-5.jpg'),
            ],
            specs: [
              'Engine: 4-Cylinder 2.0L VTEC Turbo',
              'Transmission: 6-Speed Manual',
              'Drivetrain: FWD',
              'Horsepower: 315 hp',
              'Torque: 420 Nm',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 'h2',
            name: 'Honda CR-V',
            type: 'SUV / Crossover',
            price: '₱ 2,100,000',
            description: 'The Honda CR-V is a stylish and spacious crossover SUV that blends comfort, advanced safety features, and fuel-efficient performance. It’s perfect for families and daily commuting.',
            images: [
              require('../../assets/brands/honda/crv-1.jpg'),
              require('../../assets/brands/honda/crv-2.jpg'),
              require('../../assets/brands/honda/crv-3.jpg'),
              require('../../assets/brands/honda/crv-4.jpg'),
              require('../../assets/brands/honda/crv-5.jpg'),
            ],
            specs: [
              'Engine: 4-Cylinder 2.0L e:HEV Hybrid',
              'Transmission: e-CVT',
              'Drivetrain: FWD / AWD',
              'Horsepower: 148 hp (combined: 184 hp)',
              'Torque: 335 Nm',
              'Fuel Type: Hybrid',
            ],
          },
          {
            id: 'h3',
            name: 'Honda Civic Hatchback',
            type: 'Hatchback',
            price: '₱ 1,775,000',
            description: 'The Honda Civic Hatchback combines sporty design with everyday practicality. It offers versatile cargo space, advanced tech features, and an engaging driving experience.',
            images: [
              require('../../assets/brands/honda/hatch-1.jpg'),
              require('../../assets/brands/honda/hatch-2.jpg'),
              require('../../assets/brands/honda/hatch-3.jpg'),
              require('../../assets/brands/honda/hatch-4.jpg'),
              require('../../assets/brands/honda/hatch-5.jpg'),
            ],
            specs: [
              'Engine: 4-Cylinder 1.5L VTEC Turbo',
              'Transmission: CVT',
              'Drivetrain: FWD',
              'Horsepower: 176 hp',
              'Torque: 240 Nm',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 'h4',
            name: 'Honda Accord',
            type: 'Sedan',
            price: '₱ 2,400,000',
            description: 'The Honda Accord is a premium midsize sedan known for its refined design, spacious interior, and efficient hybrid technology. It balances comfort, performance, and innovation.',
            images: [
              require('../../assets/brands/honda/accord-1.jpg'),
              require('../../assets/brands/honda/accord-2.jpg'),
              require('../../assets/brands/honda/accord-3.jpg'),
              require('../../assets/brands/honda/accord-4.jpg'),
              require('../../assets/brands/honda/accord-5.jpg'),
            ],
            specs: [
              'Engine: 4-Cylinder 2.0L e:HEV Hybrid',
              'Transmission: e-CVT',
              'Drivetrain: FWD',
              'Horsepower: 204 hp (combined)',
              'Torque: 335 Nm',
              'Fuel Type: Hybrid',
            ],
          },
          {
            id: 'h5',
            name: 'Honda HR-V',
            type: 'SUV / Crossover',
            price: '₱ 1,500,000',
            description: 'The Honda HR-V is a compact crossover that delivers stylish looks, fuel efficiency, and innovative features. Its versatile interior and smooth ride make it great for urban and suburban lifestyles.',
            images: [
              require('../../assets/brands/honda/hrv-1.jpg'),
              require('../../assets/brands/honda/hrv-2.jpg'),
              require('../../assets/brands/honda/hrv-3.jpg'),
              require('../../assets/brands/honda/hrv-4.jpg'),
              require('../../assets/brands/honda/hrv-5.jpg'),
            ],
            specs: [
              'Engine: 4-Cylinder 1.5L DOHC i-VTEC',
              'Transmission: CVT',
              'Drivetrain: FWD',
              'Horsepower: 119 hp',
              'Torque: 145 Nm',
              'Fuel Type: Gasoline',
            ],
          }
          
           
      ],    

    /************************************************************* Nissan  **********************************************************/   
    Nissan: [
        {
            id: 'n1',
            name: 'Nissan GT-R',
            type: 'Coupe / Convertible',
            price: '₱ 12,500,000',
            description: 'The Nissan GT-R is a high-performance sports car known for its aggressive design, advanced technology, and exhilarating speed. It delivers razor-sharp handling and supercar-level performance.',
            images: [
              require('../../assets/brands/nissan/gtr-1.jpg'),
              require('../../assets/brands/nissan/gtr-2.jpg'),
              require('../../assets/brands/nissan/gtr-3.jpg'),
              require('../../assets/brands/nissan/gtr-4.jpg'),
              require('../../assets/brands/nissan/gtr-5.jpg'),
            ],
            specs: [
              'Engine: 3.8L 6-Cylinder Twin-Turbo',
              'Transmission: 6-Speed Dual-Clutch',
              'Drivetrain: AWD',
              'Horsepower: 565 hp',
              'Torque: 633 Nm',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 'n2',
            name: 'Nissan Patrol',
            type: 'SUV / Crossover',
            price: '₱ 4,750,000',
            description: 'The Nissan Patrol is a full-size luxury SUV that blends off-road capabilities with refined comfort. It’s a dependable and spacious vehicle ideal for long journeys and rugged terrain.',
            images: [
              require('../../assets/brands/nissan/patrol-1.jpg'),
              require('../../assets/brands/nissan/patrol-2.jpg'),
              require('../../assets/brands/nissan/patrol-3.jpg'),
              require('../../assets/brands/nissan/patrol-4.jpg'),
              require('../../assets/brands/nissan/patrol-5.jpg'),
            ],
            specs: [
              'Engine: 5.6L 8-Cylinder',
              'Transmission: 7-Speed Automatic',
              'Drivetrain: AWD',
              'Horsepower: 400 hp',
              'Torque: 560 Nm',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 'n3',
            name: 'Nissan Navara',
            type: 'Pickup Truck',
            price: '₱ 1,630,000',
            description: 'The Nissan Navara is a rugged and reliable pickup truck that combines practicality with comfort. It’s well-suited for both urban use and heavy-duty off-road work.',
            images: [
              require('../../assets/brands/nissan/navara-1.jpg'),
              require('../../assets/brands/nissan/navara-2.jpg'),
              require('../../assets/brands/nissan/navara-3.jpg'),
              require('../../assets/brands/nissan/navara-4.jpg'),
              require('../../assets/brands/nissan/navara-5.jpeg'),
            ],
            specs: [
              'Engine: 2.5L 4-Cylinder Turbo Diesel',
              'Transmission: 7-Speed Automatic',
              'Drivetrain: 4WD',
              'Horsepower: 187 hp',
              'Torque: 450 Nm',
              'Fuel Type: Diesel',
            ],
          },
          {
            id: 'n4',
            name: 'Nissan Leaf',
            type: 'Hatchback',
            price: '₱ 2,798,000',
            description: 'The Nissan Leaf is a fully electric hatchback that offers zero-emissions driving, advanced features, and an eco-friendly alternative without sacrificing practicality.',
            images: [
              require('../../assets/brands/nissan/leaf-1.jpg'),
              require('../../assets/brands/nissan/leaf-2.jpg'),
              require('../../assets/brands/nissan/leaf-3.jpg'),
              require('../../assets/brands/nissan/leaf-4.jpg'),
              require('../../assets/brands/nissan/leaf-5.jpg'),
            ],
            specs: [
              'Engine: Electric Motor',
              'Transmission: Single-Speed',
              'Drivetrain: FWD',
              'Horsepower: 147 hp',
              'Torque: 320 Nm',
              'Fuel Type: Electric',
            ],
          },
          {
            id: 'n5',
            name: 'Nissan 370Z NISMO',
            type: 'Coupe / Convertible',
            price: '₱ 3,880,000',
            description: 'The Nissan 370Z NISMO is a performance-tuned version of the iconic Z sports car. It offers enhanced aerodynamics, firmer suspension, and a thrilling driving experience.',
            images: [
              require('../../assets/brands/nissan/370z-1.jpg'),
              require('../../assets/brands/nissan/370z-2.jpg'),
              require('../../assets/brands/nissan/370z-3.jpg'),
              require('../../assets/brands/nissan/370z-4.jpg'),
              require('../../assets/brands/nissan/370z-5.jpg'),
            ],
            specs: [
              'Engine: 3.7L 6-Cylinder',
              'Transmission: 6-Speed Manual',
              'Drivetrain: RWD',
              'Horsepower: 350 hp',
              'Torque: 374 Nm',
              'Fuel Type: Gasoline',
            ],
          },
          {
            id: 'n6',
            name: 'Nissan Sentra',
            type: 'Sedan',
            price: '₱ 1,250,000',
            description: 'The Nissan Sentra is a compact sedan that delivers comfort, style, and efficiency. It features a modern design, spacious interior, and a suite of safety technologies.',
            images: [
              require('../../assets/brands/nissan/sentra-1.jpg'),
              require('../../assets/brands/nissan/sentra-2.jpg'),
              require('../../assets/brands/nissan/sentra-3.jpg'),
              require('../../assets/brands/nissan/sentra-4.jpeg'),
              require('../../assets/brands/nissan/sentra-5.jpg'),
            ],
            specs: [
              'Engine: 2.0L 4-Cylinder',
              'Transmission: CVT',
              'Drivetrain: FWD',
              'Horsepower: 149 hp',
              'Torque: 197 Nm',
              'Fuel Type: Gasoline',
            ],
          },
           
      ],   
      
      
    /************************************************************* Ford  **********************************************************/   
    Ford: [
        {
          id: 'f1',
          name: 'Ford Ranger Raptor',
          type: 'Pickup Truck',
          price: '₱ 2,339,000',
          description: 'The Ford Ranger Raptor is a high-performance off-road pickup designed for tough terrain and aggressive driving. It combines rugged durability with advanced tech and premium comfort.',
          images: [
            require('../../assets/brands/ford/raptor-1.jpg'),
            require('../../assets/brands/ford/raptor-2.jpg'),
            require('../../assets/brands/ford/raptor-3.jpg'),
            require('../../assets/brands/ford/raptor-4.jpg'),
            require('../../assets/brands/ford/raptor-5.jpg'),
          ],
          specs: [
            'Engine: 2.0L 4-Cylinder Bi-Turbo Diesel',
            'Transmission: 10-Speed Automatic',
            'Drivetrain: 4WD',
            'Horsepower: 210 hp',
            'Torque: 500 Nm',
            'Fuel Type: Diesel',
          ],
        },
        {
          id: 'f2',
          name: 'Ford Everest',
          type: 'SUV / Crossover',
          price: '₱ 2,525,000',
          description: 'The Ford Everest is a midsize SUV that offers a strong combination of off-road capabilities, advanced safety, and spacious interior, perfect for families and adventures alike.',
          images: [
            require('../../assets/brands/ford/everest-1.jpg'),
            require('../../assets/brands/ford/everest-2.jpg'),
            require('../../assets/brands/ford/everest-3.jpg'),
            require('../../assets/brands/ford/everest-4.jpg'),
            require('../../assets/brands/ford/everest-5.jpg'),
          ],
          specs: [
            'Engine: 2.0L 4-Cylinder Bi-Turbo Diesel',
            'Transmission: 10-Speed Automatic',
            'Drivetrain: 4WD',
            'Horsepower: 210 hp',
            'Torque: 500 Nm',
            'Fuel Type: Diesel',
          ],
        },
        {
          id: 'f3',
          name: 'Ford Mustang Shelby GT500',
          type: 'Coupe / Convertible',
          price: '₱ 7,760,000',
          description: 'The Ford Mustang Shelby GT500 is the ultimate expression of Ford performance. With a supercharged 8-cylinder engine, track-ready handling, and aggressive design, it’s built for speed and dominance.',
          images: [
            require('../../assets/brands/ford/mustang-1.jpg'),
            require('../../assets/brands/ford/mustang-2.jpg'),
            require('../../assets/brands/ford/mustang-3.jpg'),
            require('../../assets/brands/ford/mustang-4.png'),
            require('../../assets/brands/ford/mustang-5.jpg'),
          ],
          specs: [
            'Engine: 5.2L Supercharged 8-Cylinder',
            'Transmission: 7-Speed Dual-Clutch Automatic',
            'Drivetrain: RWD',
            'Horsepower: 760 hp',
            'Torque: 847 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'f4',
          name: 'Ford Expedition Max',
          type: 'SUV / Crossover',
          price: '₱ 6,999,000',
          description: 'The Ford Expedition Max is a full-size luxury SUV offering massive interior space, premium features, and 8-cylinder twin-turbo performance for both comfort and capability.',
          images: [
            require('../../assets/brands/ford/expedition-1.jpg'),
            require('../../assets/brands/ford/expedition-2.jpg'),
            require('../../assets/brands/ford/expedition-3.jpg'),
            require('../../assets/brands/ford/expedition-4.jpg'),
            require('../../assets/brands/ford/expedition-5.jpg'),
          ],
          specs: [
            'Engine: 3.5L 6-Cylinder Twin-Turbo',
            'Transmission: 10-Speed Automatic',
            'Drivetrain: 4WD',
            'Horsepower: 400 hp',
            'Torque: 650 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'f5',
          name: 'Ford Bronco',
          type: 'SUV / Crossover',
          price: '₱ 4,998,000',
          description: 'The Ford Bronco is a rugged off-road SUV reimagined for modern adventurers. It boasts a retro-modern design, powerful engine options, and off-road innovations.',
          images: [
            require('../../assets/brands/ford/bronco-1.jpg'),
            require('../../assets/brands/ford/bronco-2.jpg'),
            require('../../assets/brands/ford/bronco-3.jpg'),
            require('../../assets/brands/ford/bronco-4.jpg'),
            require('../../assets/brands/ford/bronco-5.jpg'),
          ],
          specs: [
            'Engine: 2.7L 6-Cylinder Twin-Turbo',
            'Transmission: 10-Speed Automatic',
            'Drivetrain: 4WD',
            'Horsepower: 330 hp',
            'Torque: 563 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'f6',
          name: 'Ford F-150',
          type: 'Pickup Truck',
          price: '₱ 3,398,000',
          description: 'The Ford F-150 Lariat is a full-size pickup truck known for its strength, comfort, and high-end features. It delivers excellent towing capacity and a premium driving experience.',
          images: [
            require('../../assets/brands/ford/f150-1.jpg'),
            require('../../assets/brands/ford/f150-2.jpg'),
            require('../../assets/brands/ford/f150-3.jpg'),
            require('../../assets/brands/ford/f150-4.jpg'),
            require('../../assets/brands/ford/f150-5.jpg'),
          ],
          specs: [
            'Engine: 3.5L 6-Cylinder Twin-Turbo',
            'Transmission: 10-Speed Automatic',
            'Drivetrain: 4WD',
            'Horsepower: 400 hp',
            'Torque: 677 Nm',
            'Fuel Type: Gasoline',
          ],
        },           
      ],    
    /************************************************************* Chevrolet  **********************************************************/   
    Chevrolet: [
        {
          id: 'c1',
          name: 'Chevrolet Trailblazer',
          type: 'SUV / Crossover',
          price: '₱ 1,518,888',
          description: 'The Chevrolet Trailblazer is a modern crossover SUV that offers bold styling, advanced safety, and turbocharged performance perfect for urban and weekend adventures.',
          images: [
            require('../../assets/brands/chevrolet/trailblazer-1.jpg'),
            require('../../assets/brands/chevrolet/trailblazer-2.jpg'),
            require('../../assets/brands/chevrolet/trailblazer-3.jpg'),
            require('../../assets/brands/chevrolet/trailblazer-4.jpg'),
            require('../../assets/brands/chevrolet/trailblazer-5.jpg'),
          ],
          specs: [
            'Engine: 1.3L 3-Cylinder Turbo',
            'Transmission: CVT',
            'Drivetrain: FWD',
            'Horsepower: 155 hp',
            'Torque: 236 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'c2',
          name: 'Chevrolet Tahoe',
          type: 'SUV / Crossover',
          price: '₱ 7,702,888',
          description: 'The Chevrolet Tahoe is a full-size SUV with commanding presence, powerful 8-cylinder performance, and a spacious, tech-rich interior for families and luxury travel.',
          images: [
            require('../../assets/brands/chevrolet/tahoe-1.jpg'),
            require('../../assets/brands/chevrolet/tahoe-2.jpg'),
            require('../../assets/brands/chevrolet/tahoe-3.jpg'),
            require('../../assets/brands/chevrolet/tahoe-4.jpg'),
            require('../../assets/brands/chevrolet/tahoe-5.jpg'),
          ],
          specs: [
            'Engine: 5.3L 8-Cylinder',
            'Transmission: 10-Speed Automatic',
            'Drivetrain: 4WD',
            'Horsepower: 355 hp',
            'Torque: 519 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'c3',
          name: 'Chevrolet Corvette Stingray',
          type: 'Coupe / Convertible',
          price: '₱ 12,571,888',
          description: 'The Chevrolet Corvette Stingray is an American icon—an exotic mid-engine sports car that delivers thrilling performance, exotic design, and everyday drivability.',
          images: [
            require('../../assets/brands/chevrolet/corvette-1.jpg'),
            require('../../assets/brands/chevrolet/corvette-2.jpg'),
            require('../../assets/brands/chevrolet/corvette-3.jpg'),
            require('../../assets/brands/chevrolet/corvette-4.jpg'),
            require('../../assets/brands/chevrolet/corvette-5.jpg'),
          ],
          specs: [
            'Engine: 6.2L 8-Cylinder',
            'Transmission: 8-Speed Dual-Clutch',
            'Drivetrain: RWD',
            'Horsepower: 495 hp',
            'Torque: 637 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'c4',
          name: 'Chevrolet Silverado 1500',
          type: 'Pickup Truck',
          price: '₱ 5,518,888',
          description: 'The Chevrolet Silverado is a powerful and dependable full-size pickup truck with strong towing capacity, spacious cabin, and bold styling.',
          images: [
            require('../../assets/brands/chevrolet/silverado-1.jpg'),
            require('../../assets/brands/chevrolet/silverado-2.jpg'),
            require('../../assets/brands/chevrolet/silverado-3.jpg'),
            require('../../assets/brands/chevrolet/silverado-4.jpg'),
            require('../../assets/brands/chevrolet/silverado-5.jpg'),
          ],
          specs: [
            'Engine: 5.3L 8-Cylinder',
            'Transmission: 10-Speed Automatic',
            'Drivetrain: 4WD',
            'Horsepower: 355 hp',
            'Torque: 519 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'c5',
          name: 'Chevrolet Camaro',
          type: 'Coupe / Convertible',
          price: '₱ 4,066,888',
          description: 'The Chevrolet Camaro is a legendary muscle car with sharp looks and powerful performance, offering an exhilarating ride and aggressive road presence.',
          images: [
            require('../../assets/brands/chevrolet/camaro-1.jpg'),
            require('../../assets/brands/chevrolet/camaro-2.jpg'),
            require('../../assets/brands/chevrolet/camaro-3.jpg'),
            require('../../assets/brands/chevrolet/camaro-4.jpg'),
            require('../../assets/brands/chevrolet/camaro-5.jpg'),
          ],
          specs: [
            'Engine: 6.2L 8-Cylinder',
            'Transmission: 10-Speed Automatic',
            'Drivetrain: RWD',
            'Horsepower: 455 hp',
            'Torque: 617 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'c6',
          name: 'Chevrolet Trax',
          type: 'SUV / Crossover',
          price: '₱ 1,793,888',
          description: 'The Chevrolet Trax is a nimble and stylish subcompact SUV with practical features and turbocharged efficiency, ideal for city lifestyles.',
          images: [
            require('../../assets/brands/chevrolet/trax-1.jpg'),
            require('../../assets/brands/chevrolet/trax-2.jpg'),
            require('../../assets/brands/chevrolet/trax-3.jpg'),
            require('../../assets/brands/chevrolet/trax-4.jpg'),
            require('../../assets/brands/chevrolet/trax-5.jpg'),
          ],
          specs: [
            'Engine: 1.2L 3-Cylinder Turbo',
            'Transmission: 6-Speed Automatic',
            'Drivetrain: FWD',
            'Horsepower: 137 hp',
            'Torque: 220 Nm',
            'Fuel Type: Gasoline',
          ],
        },           
      ],    


    /************************************************************* Hyundai  **********************************************************/   
    Hyundai: [
        {
          id: 'h1',
          name: 'Hyundai Tucson',
          type: 'SUV / Crossover',
          price: '₱ 1,570,000',
          description: 'The Hyundai Tucson is a sleek and versatile compact SUV with a bold design, smart tech features, and comfortable driving dynamics for daily use and weekend getaways.',
          images: [
            require('../../assets/brands/hyundai/tucson-1.jpg'),
            require('../../assets/brands/hyundai/tucson-2.jpg'),
            require('../../assets/brands/hyundai/tucson-3.jpg'),
            require('../../assets/brands/hyundai/tucson-4.jpg'),
            require('../../assets/brands/hyundai/tucson-5.jpg'),
          ],
          specs: [
            'Engine: 2.0L 4-Cylinder Diesel',
            'Transmission: 8-Speed Automatic',
            'Drivetrain: FWD',
            'Horsepower: 183 hp',
            'Torque: 416 Nm',
            'Fuel Type: Diesel',
          ],
        },
        {
          id: 'h2',
          name: 'Hyundai Staria',
          type: 'Minivan / MPV',
          price: '₱ 3,030,000',
          description: 'The Hyundai Staria is a futuristic MPV designed for luxury and utility. With its spaceship-like design and advanced safety features, it redefines family and business travel.',
          images: [
            require('../../assets/brands/hyundai/staria-1.jpg'),
            require('../../assets/brands/hyundai/staria-2.jpg'),
            require('../../assets/brands/hyundai/staria-3.jpg'),
            require('../../assets/brands/hyundai/staria-4.jpg'),
            require('../../assets/brands/hyundai/staria-5.jpg'),
          ],
          specs: [
            'Engine: 2.2L 4-Cylinder Diesel',
            'Transmission: 8-Speed Automatic',
            'Drivetrain: FWD',
            'Horsepower: 177 hp',
            'Torque: 430 Nm',
            'Fuel Type: Diesel',
          ],
        },
        {
          id: 'h3',
          name: 'Hyundai Santa Fe Hybrid',
          type: 'SUV / Crossover',
          price: '₱ 2,700,000',
          description: 'The Hyundai Santa Fe Hybrid combines fuel efficiency with bold SUV styling and modern comfort. It features a smart hybrid powertrain, making it ideal for eco-conscious families.',
          images: [
            require('../../assets/brands/hyundai/santafe-1.jpg'),
            require('../../assets/brands/hyundai/santafe-2.jpg'),
            require('../../assets/brands/hyundai/santafe-3.jpg'),
            require('../../assets/brands/hyundai/santafe-4.jpg'),
            require('../../assets/brands/hyundai/santafe-5.jpg'),
          ],
          specs: [
            'Engine: 1.6L 4-Cylinder Turbo Hybrid',
            'Transmission: 6-Speed Automatic',
            'Drivetrain: AWD',
            'Horsepower: 226 hp (combined)',
            'Torque: 350 Nm',
            'Fuel Type: Hybrid (Gasoline + Electric)',
          ],
        },
        {
          id: 'h4',
          name: 'Hyundai Elantra N',
          type: 'Sedan',
          price: '₱ 2,200,000',
          description: 'The Hyundai Elantra N is a high-performance sport sedan that blends aggressive styling with track-ready capabilities. It delivers thrilling handling, powerful acceleration, and everyday drivability.',
          images: [
            require('../../assets/brands/hyundai/elantra-1.jpg'),
            require('../../assets/brands/hyundai/elantra-2.jpg'),
            require('../../assets/brands/hyundai/elantra-3.jpg'),
            require('../../assets/brands/hyundai/elantra-4.jpg'),
            require('../../assets/brands/hyundai/elantra-5.jpg'),
          ],
          specs: [
            'Engine: 2.0L 4-Cylinder Turbo',
            'Transmission: 6-Speed Manual / 8-Speed DCT',
            'Drivetrain: FWD',
            'Horsepower: 276 hp',
            'Torque: 392 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'h5',
          name: 'Hyundai Santa Cruz',
          type: 'Pickup Truck',
          price: '₱ 2,450,000',
          description: 'The Hyundai Santa Cruz blends the comfort of an SUV with the utility of a pickup, making it a perfect sport adventure vehicle for urban and outdoor lifestyles.',
          images: [
            require('../../assets/brands/hyundai/santacruz-1.jpg'),
            require('../../assets/brands/hyundai/santacruz-2.jpg'),
            require('../../assets/brands/hyundai/santacruz-3.jpg'),
            require('../../assets/brands/hyundai/santacruz-4.jpg'),
            require('../../assets/brands/hyundai/santacruz-5.jpg'),
          ],
          specs: [
            'Engine: 2.5L 4-Cylinder Turbo',
            'Transmission: 8-Speed Dual-Clutch',
            'Drivetrain: AWD',
            'Horsepower: 281 hp',
            'Torque: 421 Nm',
            'Fuel Type: Gasoline',
          ],
        },           
      ],    
        
    /************************************************************* Mazda  **********************************************************/   
    Mazda: [
        {
          id: 'm1',
          name: 'Mazda 3 Sport',
          type: 'Sedan',
          price: '₱ 1,510,000',
          description: 'The Mazda 3 Sedan offers a blend of elegant design, advanced technology, and engaging driving dynamics, making it a standout in its class.',
          images: [
            require('../../assets/brands/mazda/3s-1.jpg'),  
            require('../../assets/brands/mazda/3s-2.jpg'),
            require('../../assets/brands/mazda/3s-3.jpg'),
            require('../../assets/brands/mazda/3s-4.jpg'),
            require('../../assets/brands/mazda/3s-5.jpg'),
          ],
          specs: [
            'Engine: 2.0L 4-Cylinder',
            'Transmission: 6-Speed Automatic',
            'Drivetrain: FWD',
            'Horsepower: 153 hp',
            'Torque: 200 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'm2',
          name: 'Mazda BT-50',
          type: 'Pickup Truck',
          price: '₱ 1,430,000',
          description: 'The Mazda BT-50 combines rugged capability with refined comfort, offering a versatile pickup truck suitable for both work and leisure.',
          images: [
            require('../../assets/brands/mazda/bt50-1.jpg'),
            require('../../assets/brands/mazda/bt50-2.jpg'),
            require('../../assets/brands/mazda/bt50-3.jpg'),
            require('../../assets/brands/mazda/bt50-4.jpg'),
            require('../../assets/brands/mazda/bt50-5.jpg'),
          ],
          specs: [
            'Engine: 3.0L 4-Cylinder Turbo Diesel',
            'Transmission: 6-Speed Automatic',
            'Drivetrain: 4x2',
            'Horsepower: 187 hp',
            'Torque: 450 Nm',
            'Fuel Type: Diesel',
          ],
        },
        {
          id: 'm3',
          name: 'Mazda 2 Hatchback',
          type: 'Hatchback',
          price: '₱ 1,220,000',
          description: 'The Mazda 2 Hatchback is a compact and agile city car with upscale features, sporty handling, and impressive fuel economy.',
          images: [
            require('../../assets/brands/mazda/2hatch-1.jpg'),
            require('../../assets/brands/mazda/2hatch-2.jpg'),
            require('../../assets/brands/mazda/2hatch-3.jpg'),
            require('../../assets/brands/mazda/2hatch-4.jpg'),
            require('../../assets/brands/mazda/2hatch-5.jpg'),
          ],
          specs: [
            'Engine: 1.5L 4-Cylinder',
            'Transmission: 6-Speed Manual',
            'Drivetrain: FWD',
            'Horsepower: 110 hp',
            'Torque: 141 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'm4',
          name: 'Mazda MX-5',
          type: 'Coupe / Convertible',
          price: '₱ 2,300,000',
          description: 'The Mazda MX-5 is a lightweight, rear-wheel-drive roadster that delivers pure driving pleasure with its responsive handling and open-top experience.',
          images: [
            require('../../assets/brands/mazda/mx5-1.jpg'),
            require('../../assets/brands/mazda/mx5-2.jpg'),
            require('../../assets/brands/mazda/mx5-3.jpg'),
            require('../../assets/brands/mazda/mx5-4.jpg'),
            require('../../assets/brands/mazda/mx5-5.jpg'),
          ],
          specs: [
            'Engine: 2.0L 4-Cylinder',
            'Transmission: 6-Speed Manual',
            'Drivetrain: RWD',
            'Horsepower: 184 hp',
            'Torque: 205 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'm5',
          name: 'Mazda 3 Hatchback',
          type: 'Hatchback',
          price: '₱ 1,510,000',
          description: 'The Mazda 3 Hatchback combines sporty styling with versatile functionality, offering an engaging drive and ample cargo space.',
          images: [
            require('../../assets/brands/mazda/3hatch-1.jpg'),
            require('../../assets/brands/mazda/3hatch-2.jpg'),
            require('../../assets/brands/mazda/3hatch-3.jpg'),
            require('../../assets/brands/mazda/3hatch-4.png'),
            require('../../assets/brands/mazda/3hatch-5.jpg'),
          ],
          specs: [
            'Engine: 2.0L 4-Cylinder',
            'Transmission: 6-Speed Automatic',
            'Drivetrain: FWD',
            'Horsepower: 153 hp',
            'Torque: 200 Nm',
            'Fuel Type: Gasoline',
          ],
        },
        {
          id: 'm6',
          name: 'Mazda CX-30',
          type: 'SUV / Crossover',
          price: '₱ 1,790,000',
          description: 'The Mazda CX-30 offers a compact crossover experience with sleek design, advanced safety features, and a comfortable interior.',
          images: [
            require('../../assets/brands/mazda/cx30-1.jpg'),
            require('../../assets/brands/mazda/cx30-2.jpg'),
            require('../../assets/brands/mazda/cx30-3.jpg'),
            require('../../assets/brands/mazda/cx30-4.jpg'),
            require('../../assets/brands/mazda/cx30-5.jpg'),
          ],
          specs: [
            'Engine: 2.0L 4-Cylinder',
            'Transmission: 6-Speed Automatic',
            'Drivetrain: FWD',
            'Horsepower: 153 hp',
            'Torque: 200 Nm',
            'Fuel Type: Gasoline',
          ],
        },           
      ],    
        

      
      
    },
  };
  

  export { brands };
  export default brandData;